personality = "pragmatic"
model = "gpt-5.3-codex"
model_reasoning_effort = "high"
suppress_unstable_features_warning = true

[features]
multi_agent = true
shell_snapshot = true
unified_exec = true
# unstable
apply_patch_freeform = true
