[tools]
node = "24"
bun = "latest"
go = "prefix:1.25"
python = "3.13"
java = { version = "21", os = ["linux"] }
kotlin = { version = "latest", os = ["linux"] }
# Node Tools
biome = { version = "latest" }
prettier = { version = "latest" }
oxlint = { version = "latest" }
# CLI Tools
kubectl = { version = "latest", os = ["linux"] }
k6 = { version = "latest", os = ["linux"] }
k9s = { version = "latest", os = ["linux"] }
bob = "latest"
github-cli = { version = "latest", os = ["linux", "windows"] }
docker-cli = { version = "latest", os = ["linux"] }
docker-compose = { version = "latest", os = ["linux"] }
httpie-go = "latest"
lazydocker = "latest"
trivy = "latest"
amp = "latest"
aws-cli = "latest"
starship = "latest"
# Go Tools
air = "latest"
"aqua:joshmedeski/sesh" = { version = "latest", os = ["linux"] }
golangci-lint = "latest"
# Python Tools
uv = "latest"
"pipx:pgcli" = { version = "latest", os = ["linux"] }
"pipx:mycli" = { version = "latest", os = ["linux"] }
# Node Tools
"npm:opencode-ai" = { version = "latest", os = ["linux", "macos"] }
"npm:@frostoven/squoosh-cli" = { version = "latest" }
# To setup typescript-plugin
"npm:@astrojs/ts-plugin" = { version = "latest" }
"npm:@vue/typescript-plugin" = { version = "latest" }
"npm:typescript-svelte-plugin" = { version = "latest" }

[settings]
python.uv_venv_auto = true
python.uv_venv_create_args = ["--seed"]
pipx.uvx = true
# Always use bun since I jump around a lot between node versions.
npm.bun = true
# This setting is used to allow change version based on the idiomatic version file (e.g .nvmrc).
idiomatic_version_file_enable_tools = ["node"]
experimental = true
lockfile = true

[env]
# Auto enable corepack for node versions that support it (>=16.9.0).
MISE_NODE_COREPACK = true
